apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
spec:
  template:
    metadata:
      name: pod-javadbdev
      labels:
        app: pod-javadbdev
    spec:
      containers:
        - name: container-pod-javadbdev
          image: willianrmelo1/springweb:v1
          env:
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: PASSWORD
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: DATABASE_URL
          ports:
            - containerPort: 8080
  replicas: 2
  selector:
    matchLabels:
      app: pod-javadbdev

---

apiVersion: v1
kind: Service
metadata:
  name: nodeport-pod-javadbdev
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30002 # 30000 ~ 32767
  selector:
    app: pod-javadbdev

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  PASSWORD: bXVkYW5kbw==

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  USER: root
  DATABASE_URL: mysql://10.0.1.252:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC
