apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deploymentstg
spec:
  template:
    metadata:
      name: pod-javadbstg
      labels:
        app: pod-javadbstg
    spec:
      containers:
        - name: container-pod-javadbstg
          image: willianrmelo1/springweb:v1
          env:
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: PASSWORD
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: DATABASE_URL
          ports:
            - containerPort: 8080
  replicas: 2
  selector:
    matchLabels:
      app: pod-javadbstg

---

apiVersion: v1
kind: Service
metadata:
  name: nodeport-pod-javadbstg
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30003 # 30000 ~ 32767
  selector:
    app: pod-javadbstg
